### ISSUE TITLE
terms.mdとprivacy.mdのrename

### ISSUE THREAD

**Issue by nimiusrd** [YNUWAIWAI/werewolfguide#5]
デフォルトの言語は`en`

`*.md` => crowdinで管理
`*_en.md` => `*.md`

**Comment by ktr-skmt** [comment]
日本国法に準拠しているので原文が日本語で，英語のものは原文の英訳なんだけど，Crowdinで英文を和訳したかのように管理するのがいいのかな？

**Comment by nimiusrd** [comment]
Crowdinを使わなくても簡単に管理できるならそれでもいいですね

**Comment by nimiusrd** [comment]
`*_ja.md`は`docs/ja`に置き，crowdinの管理外にして，`*.md`にrenameする．
`yarn crowdin-download`後に`website/translated_docs`にコピーするスクリプト(node)を実行
